version: '3'
services:

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      - DATABASE_URL

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - certbot_www:/var/www/certbot/
      - ssl_certs:/etc/letsencrypt/
    depends_on:
      - flask

  certbot:
    image: certbot
    build:
      context: .
      dockerfile: Dockerfile-certbot
    volumes:
      - certbot_www:/var/www/certbot/
      - ssl_certs:/etc/letsencrypt/
volumes:
  certbot_www:
  ssl_certs:

