version: '3'
services:

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      - DATABASE_URL

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - flask

  proxy1:
    image: alpeware/chrome-headless-trunk
    volumes:
      - /tmp/chromedata:/data