version: '3'
networks:
  backend-network:
  simplisticblogger_backend-network:
    external: true
services:

  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    environment:
      - DATABASE_URL
    networks:
      - backend-network

  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    networks:
      - backend-network
      - simplisticblogger_backend-network

