version: '3'
networks:
  backend-network:
  simplisticblogger_backend-network:
    external: true
services:

  flask:
    networks:
      - backend-network

  nginx:
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
      - simplisticblogger_backend-network
    depends_on:
      - flask

