version: '3'
networks:
  backend-network-staging:
services:

  flask:
    image: webapp-flask-staging
    networks:
      - backend-network-staging

  nginx:
    image: webapp-nginx-staging
    ports:
      - 8080:80
      - 8043:443
    networks:
      - backend-network-staging
    volumes:
      - build_certbot_www:/var/www/certbot/
      - build_ssl_certs:/etc/letsencrypt/

volumes:
  build_certbot_www:
    external: true
  build_ssl_certs:
    external: true

