version: '3'
networks:
  backend-network:
  simplisticblogger_backend-network:
    external: true
services:

  flask:
    restart: "unless-stopped"
    networks:
      - backend-network

  nginx:
    restart: "unless-stopped"
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
      - simplisticblogger_backend-network
    volumes:
      - certbot_www:/var/www/certbot/
      - ssl_certs:/etc/letsencrypt/

  certbot:
    image: certbot
    restart: "unless-stopped"
    build:
      context: .
      dockerfile: Dockerfile-certbot
    volumes:
      - certbot_www:/var/www/certbot/
      - ssl_certs:/etc/letsencrypt/
volumes:
  certbot_www:
  ssl_certs:

