version: '3'
networks:
  backend-network-staging:
services:

  flask:
    image: webapp-flask-staging
    networks:
      - backend-network-staging

  nginx:
    image: webapp-nginx-staging
    ports:
      - 8080:80
      - 8043:443
    networks:
      - backend-network-staging

