FROM python:3.9.15

ENV APP /app

RUN mkdir $APP
WORKDIR $APP

EXPOSE 8000

COPY requirements.txt .
RUN pip install -r requirements.txt --extra-index-url http://my-handicapped-pet.io:3141/ilyaukin/dev --trusted-host my-handicapped-pet.io

COPY . .
RUN cd app && pip install -e . && cd ..

# use `--build-arg DATABASE_URL="$DATABASE_URL"` during build time
ARG DATABASE_URL
RUN python -m scripts.apply_migrations

CMD [ "python", "run.py" ]
