version: '3'
networks:
  backend-network:
services:

  flask:
    networks:
      - backend-network

  nginx:
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
    volumes:
      - build_certbot_www:/var/www/certbot/
      - build_ssl_certs:/etc/letsencrypt/

volumes:
  build_certbot_www:
    external: true
  build_ssl_certs:
    external: true

