FROM python:3.9.15

ENV APP /app

RUN mkdir $APP
WORKDIR $APP

EXPOSE 5000

COPY requirements.txt .
RUN pip install -r requirements.txt --extra-index-url http://my-handicapped-pet.io:3141/ilyaukin/dev --trusted-host my-handicapped-pet.io

COPY . .
RUN cd app && pip install -e . && cd ..

RUN python -m scripts.apply_migrations

CMD [ "uwsgi", "--ini", "app.ini" ]
