# This workflow triggers Check-in develop in sadist-ci repo

name: Check-in develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Trigger sadist-ci build
    - uses: informaticsmatters/trigger-ci-action@v1
      with:
        ci-owner: ilyaikin
        ci-repository: sadist-ci
        ci-ref: refs/heads/develop
        ci-user: ilyaukin
        ci-user-token: ${{ secrets.ACCESS_TOKEN }}
        ci-name: Check-in develop
