# This is a workflow for merge to master, triggered by sadist-ci

name: Check-in master

# Controls when the action will run. Triggers the workflow manually
on:
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out sadist-be under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Merges develop to master
    - uses: bambamboole/gha-upmerge@master
      with:
        stable_branch: master
        development_branch: develop
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}